name: Publish Pypi

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Installs dependencies"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
      - name: "Builds and uploads to PyPI"
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          body: '[More see Changelog](https://github.com/MerleLiuKun/flask-twitter/blob/master/CHANGELOG.md)'
          files: 'Flask-Twitter-*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}